#!/usr/bin/env ruby

require_relative '../../lib/colors'
require_relative '../../lib/util'

$colors = $data[:terminal].split(' ').map do |e|
  get_color(e)
end

puts <<EOL
[Scheme]
Name=#{$name}
ColorForeground=#{get_color('fg')}
ColorBackground=#{get_color('bg')}
TabActivityColor=#{get_color($data[:activity])}
ColorPalette=#{$colors.join(';')}
ColorSelectionUseDefault=FALSE
ColorSelection=#{get_color('bg')}
ColorSelectionBackground=#{get_color($data[:selection])}
ColorCursorUseDefault=FALSE
ColorCursor=#{get_color($data[:cursor])}
EOL
